### ISSUE TITLE
cudoctl won't work on python < 3.11, but pyproject.toml suggests >= 3.8

### ISSUE THREAD

**Issue by funkypenguin** [cudoventures/cudo-compute-python-client#6]
Hey guys,

I'm working with the SkyPilot devs on integrating Cudo support (https://docs.skypilot.co/en/latest/getting-started/installation.html#cudo-compute) into their helm chart. 

We ran into an unexpected issue trying to run `cudoctl` on our image though (Python 3.10), as detailed below:

```
  Cudo: disabled
    Reason [compute]: ImportError: cannot import name 'timeout' from 'asyncio' (/usr/local/lib/python3.10/asyncio/__init__.py)
  Kubernetes: enabled [compute]
```

I'm not a Python guy, but I'm told this is because `asyncio.timeout` was only introduced in Python 3.11 - the devs pointed me to https://github.com/cudoventures/cudo-compute-python-client/blob/main/pyproject.toml#L13, which suggests that `cudoctl` **should** be working in our Python 3.10 environment.

```
root@skypilot-dev-api-server-855cbc4cd7-fmpd7:/# python -c "import sys, asyncio; print(sys.version); print('has asyncio.timeout?', hasattr(asyncio, 'timeout'))"
3.10.18 (main, Sep 30 2025, 00:42:07) [GCC 14.2.0]
has asyncio.timeout? False
root@skypilot-dev-api-server-855cbc4cd7-fmpd7:/#alerts 
```

Is there a way to make `cudoctl` "fall back" to older Python versions if necessary?

Thanks!
D

**Comment by funkypenguin** [comment]
Hey folks,

Any update on this one? I've got a client anxious to start using cudo who is blocked by this issue :(

D
